### ISSUE TITLE
"Problem loading the following folders" Error Message

### ISSUE THREAD

**Issue by weslebsack** [mrneo240/GDMENUCardManager#3]
**Issue:**
When loading the SD card, the application presents an error message that reads, "Problem loading the following folder(s):" followed by an ordered list of every folder after "01" (GDMENU)

**OS:** Windows 10

**Comment by mrneo240** [comment]
Need more info. 

Also can it be replicated on the original GDMENUCardManager?

**Comment by mrneo240** [comment]
I believe fixed by #7
