### ISSUE TITLE
GDMENU is listed as the first game, taking the place of the actual first game and mis-linking GDI's

### ISSUE THREAD

**Issue by weslebsack** [mrneo240/GDMENUCardManager#4]
**Issue:**
GDMENU is listed as the first game, taking the place of the actual first game. From there, the linked GDI is pushed to the following thumbnail. For example, if I loaded three games to the SD Card (Chu Chu Rocket, Crazy Taxi and Ready 2 Rumble Boxing) plus GDMENU, the menu will display the following thumbnails: GDMENU, Chu Chu Rocket and Crazy Taxi – ignoring Ready to Rumble. If I select GDMENU, it'll boot Chu Chu Rocket. If I select Chu Chu Rocket, it'll boot Crazy Taxi.

**OS:**
Windows 10

**Comment by mrneo240** [comment]
Will investigate with the same game list, also this software is openMenu not GDMENU

Please post OPENMENU.INI as found in the application folder

**Comment by mrneo240** [comment]
closed for inactivity. Please file a new issue if the issue is still present.
